### ISSUE TITLE
'Start Pixel Perfect' and toolbar button don't work when DevTools are already opened

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#1]
When Pixel Perfect is installed while the DevTools are opened, the _Start Pixel Perfect_ button in the popup doesn't do anything. Also the toolbar button doesn't work when DevTools are already opened

Tested with Firefox 39.0a1 + Pixel Perfect 2.0b1 on Win8.1.

Sebastian

**Comment by janodvarko** [comment]
Thanks for the report Sebastian.
Patch committed, please verify.

Honza

**Comment by SebastianZ** [comment]
Works. Thanks!

Sebastian
