### ISSUE TITLE
About dialog is a little bit too small

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#11]
The _About Pixel Perfect_ dialog is a bit to small, so it's showing a scrollbar.
![About Pixel Perfect](https://cloud.githubusercontent.com/assets/958943/6428472/cc6847b2-bfa3-11e4-8b19-c9e82d883f29.png)

It should be made a bit higher, so everything is visible.

Sebastian

**Comment by janodvarko** [comment]
This is the default size of the dialog that changes dynamically as the list of  contributors/translators is modified. You might consider to file a platform bug that computes different default size.

Honza

**Comment by SebastianZ** [comment]
> You might consider to file a platform bug that computes different default size.

Created [bug 1139182](https://bugzilla.mozilla.org/show_bug.cgi?id=1139182).

Sebastian
