### ISSUE TITLE
Inconsistent naming of 'Pixel Perfect'

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#12]
Sometimes 'Pixel Perfect' is written with space between both words, sometimes not. See the about dialog:
![About Pixel Perfect](https://cloud.githubusercontent.com/assets/958943/6428482/2d30b570-bfa4-11e4-9b41-83a63096a5d6.png)

It should be changed, so it is 'Pixel Perfect' (with space) everywhere.

Tested with Firefox 39.0a1 + Pixel Perfect 2.0b1 on Win8.1.

Sebastian

**Comment by aliuk2012** [comment]
Very odd there appears to be two different About pages floating about. One just mentions @janodvarko as the creator with no other Developers and then theres this version which says @ibuck is the creator.

**Comment by janodvarko** [comment]
This should be fixed when PP final is uploaded and approved on AMO
Honza

**Comment by mbuckley** [comment]
Can we close the original issue re: 'PixelPerfect' should be 'Pixel Perfect' ? This appears to be fixed now and consistent.

**Comment by janodvarko** [comment]
Yep, things seem to be consistent now.

@aliuk2012 please let me know if we should reopen

Honza
