### ISSUE TITLE
SVGs are displayed pixelated

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#15]
When an SVG image is added and scaled, it is displayed pixelated. As it is a vector format, it should be displayed as such allowing to be Pixel Perfect. :-)

Tested with Firefox 39.0a1 + Pixel Perfect 2.0b1 on Win8.1.

Sebastian

**Comment by janodvarko** [comment]
Should be fixed now, thanks for the report.

Honza

**Comment by SebastianZ** [comment]
Yes, works great now. Thanks for the fast fix, Honza!

Sebastian
