### ISSUE TITLE
Positioning should be absolute by default

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#18]
The positioning of layers should be absolute by default, not fixed as it is currently the case.
Having fixed positioning for layers causes problems when you have layouts, which don't completely fit into the viewport.

Sebastian

**Comment by janodvarko** [comment]
Thanks for the report.
Honza

**Comment by joallard** [comment]
I see this has been discussed in #49, but I'll keep it here under the right title. Would you please re-open or check, I'm getting this in Aurora/45 and v2.0.9.

**Comment by SebastianZ** [comment]
I can confirm this. Because this is obviously caused by a change in the browser (as it's working in FF 43.0), I've created a [new issue](https://github.com/firebug/pixel-perfect/issues/73) for it.

Sebastian
