### ISSUE TITLE
UI should be integrated into the DevTools

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#2]
The UI of Pixel Perfect should be integrated into the DevTools like earlier versions of it were integrated in Firebug as a separate panel.

![Pixel Perfect 1.8 in Firebug 2.0.8](https://cloud.githubusercontent.com/assets/958943/6428187/4dd6b862-bf98-11e4-96de-e664f68a7a13.png)

Sebastian

**Comment by janodvarko** [comment]
Why?

Honza

**Comment by SebastianZ** [comment]
Because it is an extension to the DevTools, it solves #14 and it avoids overlapping the browser content.

Why was it implemented as detached window?

Sebastian

**Comment by janodvarko** [comment]
> Because it is an extension to the DevTools

Implementing a panel if not a must for DevTools extensions. Every extension should rather avoid the temptation to have entire new panel.

> it solves #14 

A new DevTools panel is not needed for this report, resizable border would be good enough.

> and it avoids overlapping the browser content.

The popup panel can be simply moved away from the browser window.

> Why was it implemented as detached window?

Avoid annoying switching between panels (e.g. Inspector <-> Style Editor <-> Pixel Perfect) and make the UI addition minimal (there is only one button in the UI). The user can tweak the HTML/CSS while having PP panel opened at the same time if needed.

Honza

**Comment by SebastianZ** [comment]
> > Why was it implemented as detached window?
> 
> Avoid annoying switching between panels (e.g. Inspector <-> Style Editor <-> Pixel Perfect) and make the UI addition minimal (there is only one button in the UI). The user can tweak the HTML/CSS while having PP panel opened at the same time if needed.

Sounds reasonable. I'm still not completely convinced that a separate window is the best solution for this. (A new main panel may not be the best solution either.) Though feel free to close this issue.

Sebastian
