### ISSUE TITLE
Describe how to set up a dev environment for Pixel Perfect

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#25]
As far as I saw there is no description so far on how to configure a development environment for Pixel Perfect. There are only vague hints by the links provided within the _Further Resources_ section of the  README.md.

Like for Firebug.next there should be the detailed steps described how to configure your system to be able to hack on Pixel Perfect.

Sebastian

**Comment by janodvarko** [comment]
Good point, readme file updated.
Honza
