### ISSUE TITLE
Panel.show() method is an unsupported feature.

### ISSUE THREAD

**Issue by aliuk2012** [firebug/pixel-perfect#33]
Running jpm run -b nightly throws this warning in the terminal

> console.warn: pixel-perfect: Passing a DOM node to Panel.show() method is an unsupported feature that will be soon replaced. See: https://bugzilla.mozilla.org/show_bug.cgi?id=878877

Already reference here: https://github.com/firebug/pixel-perfect/blob/master/lib/first-run.js#L62-68

**Comment by janodvarko** [comment]
Should be fixed now.
Honza
