### ISSUE TITLE
Improve scale input

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#4]
Instead of having a text input for the size of the layer, it would make more sense to have an `<input type="number">` or a slider like for the opacity, so it's easier to adjust the value.

Also it is not possible to choose a float value, so you can't size the layer to e.g. half of its original size or to 150%.

Sebastian

**Comment by mbuckley** [comment]
Feedback from user Viplab Shahi also suggested a way to apply negative scale.

**Comment by janodvarko** [comment]
Yes, agree, this should be improved but, why the scaling is actually useful when the overlay is already created in desired dimensions?

Honza

**Comment by mbuckley** [comment]
@janodvarko Not exactly sure either..Personally I would not use this feature and instead would be testing with two images regular and 2x images instead of trying to scale. Maybe we could get an example illustrating how this would actually be used?

**Comment by SebastianZ** [comment]
One use case for scaling is surely when the whole page is zoomed, but that's already working nicely with the layers. Another one is reusing the same layer for differently sized items on the page, e.g. for tiles.

That said, I'm not a web designer and I don't know how big the use case for scaling actually is. So if there's a valid use case for it, it should be made as easy as possible to do so.

Sebastian

**Comment by janodvarko** [comment]
> Maybe we could get an example illustrating how this would actually be used?

Do you know someone (e.g. a professional designer) who could give as such example?

Honza

**Comment by voxpelli** [comment]
I had a reference 2x image that I wanted to scale down to half the size to check my design against, would really like a float value or percentage value for that – `0.5` or `50%`

**Comment by janodvarko** [comment]
Floating number can be now inserted into the input (e.g. 0.5)

The patch is in Pixel Perfect 2.0.5

https://github.com/firebug/pixel-perfect/releases

Honza
