### ISSUE TITLE
The 'Start Pixel Perfect' button doesn't work on OSX

### ISSUE THREAD

**Issue by janodvarko** [firebug/pixel-perfect#42]
The subject pretty mush says it all. Clicking the 'Start  Pixel Perfect" button doesn't open the Pixel Perfect  popup panel on OSX.

Honza

**Comment by mbuckley** [comment]
Works for me on yosemite. Was this fixed?

**Comment by janodvarko** [comment]
Hmm, works for me too now. Not sure what happened yesterday.
Closing...
Honza
