### ISSUE TITLE
Allow to change the layer order

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#5]
The user should have control over the order of the layers to solve overlaying problems.

This could be achieved via allowing to drag & drop within the list of layers or displaying buttons to move the selected layer up or down.

Sebastian

**Comment by Vuwij** [comment]
I don't understand, I can select the sorting layer but cannot change the order within that layer? Without turning of pixel perfect

**Comment by janodvarko** [comment]
Sorry, I don't understand what you mean...

If you want to change order of created layers, you can use drag-and-drop (of layers) within the layer list.

Honza
