### ISSUE TITLE
Allow to resize a layer via handles on its borders/corners

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#6]
A layer should allow to be resized within the page using handles on its borders/corners like graphics programs do it.

Sebastian

**Comment by janodvarko** [comment]
@ibuck would this be actually useful?

Honza

**Comment by mbuckley** [comment]
@janodvarko Short answer: no

I can't think of a valid use-case for this. In general, a developer would not want to resize an overlay because it will already be exported at the desired dimensions to match the design.

**Comment by janodvarko** [comment]
Yep, that's what I thought

Honza

**Comment by SebastianZ** [comment]
So what about the scaling feature in general? Should it be removed then?
The decision on this has influence on #4 and #21 and maybe other issues.

Sebastian

**Comment by janodvarko** [comment]
It's an adept for removal, we'll discuss that on our meeting.

Honza
