### ISSUE TITLE
firefox crashes on refresh with pixel perfect turned on

### ISSUE THREAD

**Issue by sviplab** [firebug/pixel-perfect#61]
If browser page is refreshed at the time of pixel perfect turned on then it crashes the browser,
i don't think it is the issue of browser. Because of pixel perfect, it is crashing.

Viplab

**Comment by janodvarko** [comment]
What browser version do you use?

Honza

**Comment by fflorent** [comment]
Hi,

We would need more information to investigate:
1. What version of Firefox do you use? And have you got the latest (final 2.0.2) version of Pixel Perfect?
2. When Firefox crashes, a window appears asking you if you want to send a crash report (as [explained here](https://support.mozilla.org/en-US/kb/mozillacrashreporter)). Have you reported it?

Florent

**Comment by sviplab** [comment]
I am using the firefox 36.0.4 and pixel perfect 2.0.2

**Comment by fflorent** [comment]
Oh, thanks for the report. I could reproduce that. Here are the crash reports:
https://crash-stats.mozilla.com/report/index/bp-c112bf23-8e8f-4755-bac3-2afc52150330
https://crash-stats.mozilla.com/report/index/bp-d27c8cb4-b23f-4bc7-a847-b4e7f2150330

Florent

**Comment by fflorent** [comment]
Also reproduced with Firefox 37.

Florent

**Comment by janodvarko** [comment]
What about Firefox 38?

Honza

**Comment by fflorent** [comment]
It works fine. Probably worth to bisect that.

Florent

**Comment by janodvarko** [comment]
Yes please!

Honza

**Comment by fflorent** [comment]
Sorry, the ftp.mozilla.org site is tonight terribly slow. Here is the command with the current regression window:

``` shell
mozregression --good=2015-01-22 --bad=2015-01-12 --app=firefox --find-fix --addon=pixelperfectplugin@openhouseconcepts.com-2.0.2.xpi  --bits=64
```

BTW, Honza, can you reproduce it too?

Florent

**Comment by janodvarko** [comment]
Yep I can also reproduce that. Here is my crash report
https://crash-stats.mozilla.com/report/index/2265eda4-75c2-43be-b2a9-0f9b32150331

Honza

**Comment by janodvarko** [comment]
@fflorent: does my patch solve the problem for you?
(please let me know asap, I'd like to update AMO)

Honza

**Comment by janodvarko** [comment]
Here is an online version for testing
http://softwareishard.com/temp/pixel-perfect/pixelperfect-2.0.3.xpi

There will be a post on hacks.mozilla later today, so I am already trying to pass review on AMO.

Honza

**Comment by fflorent** [comment]
Works for me now. @sviplab does it for you?

Florent

**Comment by janodvarko** [comment]
Thanks Florent for quick response!

Honza

**Comment by sviplab** [comment]
Yeah it works for me too. Thank You @janodvarko and @fflorent 

Viplab

**Comment by fflorent** [comment]
Thanks you for the report and for the feedback :).

Florent

**Comment by janodvarko** [comment]
Awesome, new version 2.0.3 (with the patch included) already uploaded and approved on AMO
https://addons.mozilla.org/cs/firefox/addon/pixel-perfect/

Honza

**Comment by janodvarko** [comment]
Related bugzilla bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1149932

Honza
