### ISSUE TITLE
Added layer has position:fixed on firefox < 38

### ISSUE THREAD

**Issue by oshybystyi** [firebug/pixel-perfect#63]
When I add a layer in firefox 37.0.1 (ubuntu) when scrolling vertically its y coordinate also updates (looks like effect of css position:fixed).

Do not notice same behavior on firefox nightly (40.0a1)

Bug can be reproduced on pixel-perfect 2.0.4, 2.0.5

Ubuntu 14.04, firebug is not installed.

**Comment by oshybystyi** [comment]
It is hard to defend that logic, but maybe the problem in jpm, trying to build xpi with cfx, but run into problem:
`cuddlefish.manifest.UnreachablePrefixError: Sorry, but the 'main' file (/home/oleksandr/projects/volunteer/firebug-pixel-perfect/index.js) in package pixel-perfect is outside that package's 'lib' directory (/home/oleksandr/projects/volunteer/firebug-pixel-perfect/lib), so I cannot construct a URI to reach it.`

Update:

was able to `cfx xpi--package-path=node_modules` - but addon does not work (it show up in addon list but icon is not shown on toolbar)

**Comment by janodvarko** [comment]
You need jpm to build the xpi (cfx isn't supported anymore)

Read also wiki
https://github.com/firebug/pixel-perfect/wiki/Developer-Guide#build-xpi

> When I add a layer in firefox 37.0.1 (ubuntu) when scrolling vertically its y coordinate also updates (looks like effect of css position:fixed).

Can you try to build the xpi with different css (not fixed) and see if it helps?

Honza

**Comment by janodvarko** [comment]
Also, this might be related to changes I did in #61 due to the following platform error:
https://bugzilla.mozilla.org/show_bug.cgi?id=1149932

I'd recommend to use Firefox Developer Edition (at least till 38 is out)
https://www.mozilla.org/en-US/firefox/developer/

Honza

**Comment by oshybystyi** [comment]
> Can you try to build the xpi with different css (not fixed) and see if it helps?

Oh, I see that my explanation might be misleading. Here is a video, so you can understand better https://www.dropbox.com/s/37ghnwtt37znzmx/pixel-perfect-bug.avi?dl=0

> Also, this might be related to changes I did in #61

I don't think those are related.

**Comment by janodvarko** [comment]
If I understand correctly the layer isn't scrolling with the content, right?

I don't know how to fix it for 37 and I'd recommend to use Firefox Developer Edition (at least till 38 is out) https://www.mozilla.org/en-US/firefox/developer/

Honza

**Comment by janodvarko** [comment]
Patch provided by: Oleksandr Shybystyi

Closing

Honza

**Comment by janodvarko** [comment]
Pixel Perfect 2.0.6 with the patch included is waiting for AMO review now...

Honza

**Comment by oshybystyi** [comment]
That's cool :+1:

**Comment by janodvarko** [comment]
And now it's online on AMO ;-)

Honza
