### ISSUE TITLE
Closed PixelPerfect-Window reopens after Switching Tabs

### ISSUE THREAD

**Issue by jnachtigall** [firebug/pixel-perfect#69]
Easy to reproduce (FF42, current PixelPerfect version):
1. Close PP window
2. Click on another tab
3. Go back to tab with closed PP window => PP window is open again, albeit I closed it previously

**Comment by janodvarko** [comment]
Can you please verify using this temp build?
http://janodvarko.cz/temp/pixel-perfect/pixelperfectplugin-2.0.8issue69.xpi

Thanks for the report!
Honza

**Comment by jnachtigall** [comment]
Yep, this fixes the issue. :+1:

**Comment by janodvarko** [comment]
Thanks for the update!
I've just released v0.2.9
Honza
