### ISSUE TITLE
pixel-perfect crashes when making changes in devtools

### ISSUE THREAD

**Issue by travis-bradbury** [firebug/pixel-perfect#72]
I was able to replicate the issue with a new Firefox profile and after building the extension using this repository.
1. Start Pixel Perfect
   - Changing layers, moving the image, locking, and inverting appears to work fine.
2. Click the 'pick an element' button or attempt to change styles in the Dev Tools DOM and Style Editor. The inserted image disappears and the Pixel Perfect window closes.

This issue only appears to have started since updating Firefox Developer Edition this morning. I'm using 45.0a2 (2015-12-22).

**Comment by janodvarko** [comment]
Reported here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1236868

Honza

**Comment by janodvarko** [comment]
@radiosman here is a test build with a patch that should fix the problem
http://janodvarko.cz/temp/pixel-perfect/pixelperfectplugin-2.0.9.72.xpi

Could you please verify and let me know if it works for you now?

Thanks!
Honza

**Comment by travis-bradbury** [comment]
@janodvarko sorry I'm so long in getting back to you. That appears to have solved the problem.

**Comment by janodvarko** [comment]
Thanks for the update!

Honza
